name = "diary-chain"
main = "frontend/src/worker.js"
compatibility_date = "2026-06-10"

[assets]
directory = "./frontend/dist"
binding = "ASSETS"

[[routes]]
pattern = "diary.io99.xyz"
custom_domain = true
